CREATE SEQUENCE BORROWER_ID_SEQ;
CREATE SEQUENCE INVESTOR_ID_SEQ;
CREATE SEQUENCE LOAN_DETAIL_ID_SEQ;
CREATE SEQUENCE EMPLOYEE_ID_SEQ;
CREATE SEQUENCE LOAN_PARTICIPATION_DETAIL_ID_SEQ;
CREATE SEQUENCE LOAN_PAYMENT_DETAIL_ID_SEQ;


CREATE TABLE BORROWER (
  ID                  BIGINT       NOT NULL DEFAULT NEXTVAL('BORROWER_ID_SEQ') PRIMARY KEY,
  NAME                VARCHAR(100) NOT NULL,
  MOBILE              BIGINT NOT NULL,
  ADDRESS             VARCHAR(100),
  PAN                 VARCHAR(10),
  CIBIL_SCORE         BIGINT,
  BGV_STATUS           VARCHAR(10)
);

CREATE TABLE INVESTOR (
  ID                  BIGINT       NOT NULL DEFAULT NEXTVAL('INVESTOR_ID_SEQ') PRIMARY KEY,
  NAME                VARCHAR(100) NOT NULL,
  MOBILE              BIGINT NOT NULL,
  ADDRESS             VARCHAR(100)
);

CREATE TABLE EMPLOYEE (
  ID                  BIGINT       NOT NULL DEFAULT NEXTVAL('EMPLOYEE_ID_SEQ') PRIMARY KEY,
  NAME                VARCHAR(100) NOT NULL,
  MOBILE              BIGINT
);

CREATE TABLE LOAN_DETAIL (
  ID                 BIGINT       NOT NULL DEFAULT NEXTVAL('LOAN_DETAIL_ID_SEQ') PRIMARY KEY,
  DESCRIPTION        VARCHAR(100) NOT NULL,
  INTEREST_RATE      BIGINT NOT NULL,
  AMOUNT             BIGINT NOT NULL,
  TENURE             VARCHAR(50) NOT NULL,
  START_DATE         VARCHAR(100),
  BORROWER_ID        BIGINT,
  STATUS             VARCHAR(40),
  NO_OF_INVESTORS    BIGINT,
  ASSIGNED_TO        BIGINT,
  APPROVED_BY        BIGINT,
  FOREIGN KEY (BORROWER_ID) REFERENCES BORROWER(ID),
  FOREIGN KEY (ASSIGNED_TO) REFERENCES EMPLOYEE(ID),
  FOREIGN KEY (APPROVED_BY) REFERENCES EMPLOYEE(ID)
);

CREATE TABLE LOAN_PARTICIPATION_DETAIL (
ID                 BIGINT       NOT NULL DEFAULT NEXTVAL('LOAN_PARTICIPATION_DETAIL_ID_SEQ') PRIMARY KEY,
DESCRIPTION        VARCHAR(100) NOT NULL,
INVESTOR_ID        BIGINT,
AMOUNT             BIGINT,
LOAN_DETAIL_ID     BIGINT,
FOREIGN KEY (INVESTOR_ID) REFERENCES INVESTOR(ID),
FOREIGN KEY (LOAN_DETAIL_ID) REFERENCES LOAN_DETAIL(ID));

CREATE TABLE LOAN_PAYMENT_DETAIL(
ID                 BIGINT       NOT NULL DEFAULT NEXTVAL('LOAN_PAYMENT_DETAIL_ID_SEQ') PRIMARY KEY,
DESCRIPTION        VARCHAR(100) NOT NULL,
BORROWER_ID BIGINT,
AMOUNT BIGINT,
INTEREST BIGINT,
LOAN_DETAIL_ID      BIGINT,
FOREIGN KEY (LOAN_DETAIL_ID) REFERENCES LOAN_DETAIL(ID));
