INSERT INTO BORROWER (ID,NAME,MOBILE,ADDRESS,PAN,CIBIL_SCORE,BGV_STATUS) VALUES(BORROWER_ID_SEQ.NEXTVAL, 'ALLEN', '9876543210', 'CHENNAI','ALLENPAN', 8.5, 'OK');
INSERT INTO BORROWER  (ID,NAME,MOBILE,ADDRESS,PAN,CIBIL_SCORE,BGV_STATUS) VALUES(BORROWER_ID_SEQ.NEXTVAL, 'JOHN', '9876543211', 'CHENNAI','JOHNPAN', 9, 'OK');
INSERT INTO BORROWER (ID,NAME,MOBILE,ADDRESS,PAN,CIBIL_SCORE,BGV_STATUS) VALUES(BORROWER_ID_SEQ.NEXTVAL, 'SMITH', '9876543212', 'CHENNAI','SMITHPAN', 7, 'OK');
INSERT INTO BORROWER (ID,NAME,MOBILE,ADDRESS,PAN,CIBIL_SCORE,BGV_STATUS) VALUES(BORROWER_ID_SEQ.NEXTVAL, 'BRUNO', '9876543213', 'CHENNAI','BRUNOPAN', 9.5, 'OK');

INSERT INTO INVESTOR(ID,NAME,MOBILE,ADDRESS) VALUES(INVESTOR_ID_SEQ.NEXTVAL, 'ANNA', '9876543220', 'CHENNAI');
INSERT INTO INVESTOR(ID,NAME,MOBILE,ADDRESS) VALUES(INVESTOR_ID_SEQ.NEXTVAL, 'MARIA', '9876543221', 'CHENNAI');
INSERT INTO INVESTOR(ID,NAME,MOBILE,ADDRESS) VALUES(INVESTOR_ID_SEQ.NEXTVAL, 'SARA', '9876543222', 'CHENNAI');
INSERT INTO INVESTOR(ID,NAME,MOBILE,ADDRESS) VALUES(INVESTOR_ID_SEQ.NEXTVAL, 'DIDI', '9876543223', 'CHENNAI');

INSERT INTO EMPLOYEE(ID,NAME,MOBILE) VALUES(EMPLOYEE_ID_SEQ.NEXTVAL, 'SURESH', '1234567890');